name: cosmos
version: 0.1.0
publish_to: none
environment:
  sdk: '^3.6.1'
description: A new Flutter project.
dependencies:
  audio_service: ^0.18.17
  background_downloader: ^8.9.4
  copy_with_extension: '^6.0.1'
  dio: '^5.8.0+1'
  equatable: '^2.0.7'
  flutter:
    sdk: flutter
  flutter_riverpod: '^2.6.1'
  freezed_annotation: '^2.4.4'
  json_annotation: '^4.9.0'
  just_audio: ^0.9.46
  path_provider: '^2.1.5'
  riverpod_annotation: '^2.6.1'
  rxdart: ^0.28.0
  video_player: ^2.9.2
dev_dependencies:
  build_runner: '^2.4.15'
  copy_with_extension_gen: '^6.0.1'
  custom_lint: '^0.7.3'
  flutter_flavorizr: '^2.2.3'
  flutter_launcher_icons: '^0.14.3'
  flutter_lints: '^5.0.0'
  flutter_native_splash: '^2.4.4'
  flutter_test:
    sdk: flutter
  freezed: '^2.5.8'
  json_serializable: '^6.9.4'
  pubspec_dependency_sorter: '^1.0.5'
  riverpod_generator: '^2.6.4'
  riverpod_lint: '^2.6.4'
flutter:
  uses-material-design: true
  assets:
    - assets/common/
flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: assets/common/app-icon.png
  image_path_ios_dark_transparent: assets/common/app-icon-transparent.png
  image_path_android: assets/android/app-icon-android.png
  adaptive_icon_background: assets/android/app-icon-background.png
  adaptive_icon_foreground: assets/android/app-icon-foreground.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/common/app-icon.png
flutter_native_splash:
  color: '#ffffff'
  color_android: '#ffffff'
  color_dark_android: '#121212'
  color_ios: '#ffffff'
  color_dark_ios: '#121212'
  color_web: '#ffffff'
  color_dark_web: '#121212'
  image: assets/android/app-icon-foreground.png
flavorizr:
  ide: vscode
  app:
    android:
      flavorDimensions: flavor-type
  flavors:
    dev:
      app:
        name: Cosmos Dev
      android:
        applicationId: com.paulyswen.cosmos.dev
        icon: assets/dev/app-icon.png
        adaptiveIcon:
          foreground: assets/dev/app-icon-foreground.png
          background: assets/android/app-icon-background.png
      ios:
        bundleId: com.paulyswen.cosmos.dev
        icon: assets/dev/app-icon.png
    stg:
      app:
        name: Cosmos Stg
      android:
        applicationId: com.paulyswen.cosmos.stg
        icon: assets/stg/app-icon.png
        adaptiveIcon:
          foreground: assets/stg/app-icon-foreground.png
          background: assets/android/app-icon-background.png
      ios:
        bundleId: com.paulyswen.cosmos.stg
        icon: assets/stg/app-icon.png
    prod:
      app:
        name: Cosmos
      android:
        applicationId: com.paulyswen.cosmos
        icon: assets/prod/app-icon.png
        adaptiveIcon:
          foreground: assets/prod/app-icon-foreground.png
          background: assets/android/app-icon-background.png
      ios:
        bundleId: com.paulyswen.cosmos
        icon: assets/prod/app-icon.png
