name: cosmos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_flavorizr: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/common/

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/common/app-icon.png"
  image_path_ios_dark_transparent: "assets/common/app-icon-transparent.png"
  image_path_android: "assets/android/app-icon-android.png"
  adaptive_icon_background: "assets/android/app-icon-background.png"
  adaptive_icon_foreground: "assets/android/app-icon-foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/common/app-icon.png"

flutter_native_splash:
  color: "#ffffff"
  color_android: "#ffffff"
  color_dark_android: "#121212"
  color_ios: "#ffffff"
  color_dark_ios: "#121212"
  color_web: "#ffffff"
  color_dark_web: "#121212"
  image: "assets/android/app-icon-foreground.png"

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
  
  flavors:
    dev:
      app:
        name: "Cosmos Dev"
      android:
        applicationId: "com.paulyswen.cosmos.dev"
        icon: "assets/dev/app-icon.png"
        adaptiveIcon:
          foreground: "assets/dev/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.paulyswen.cosmos.dev"
        icon: "assets/dev/app-icon.png"

    stg:
      app:
        name: "Cosmos Stg"
      android:
        applicationId: "com.paulyswen.cosmos.stg"
        icon: "assets/stg/app-icon.png"
        adaptiveIcon:
          foreground: "assets/stg/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.paulyswen.cosmos.stg"
        icon: "assets/stg/app-icon.png"
    prod:
      app:
        name: "Cosmos"
      android:
        applicationId: "com.paulyswen.cosmos"
        icon: "assets/prod/app-icon.png"
        adaptiveIcon:
          foreground: "assets/prod/app-icon-foreground.png"
          background: "assets/android/app-icon-background.png"
      ios:
        bundleId: "com.paulyswen.cosmos"
        icon: "assets/prod/app-icon.png"